# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-15 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user1',
            fields=[
                ('uname', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pwrd', models.IntegerField()),
                ('actbal', models.IntegerField(default=10000)),
                ('splitbal', models.IntegerField(default=0)),
                ('paidto', models.CharField(default='None', max_length=20)),
            ],
        ),
    ]
